set_false_path -from [get_cells filter2D_hls_CONTROL_BUS_s_axi_U/int_rows_reg[*]]
set_false_path -from [get_cells filter2D_hls_CONTROL_BUS_s_axi_U/int_cols_reg[*]]
set_false_path -from [get_cells filter2D_hls_CONTROL_BUS_s_axi_U/int_channels_reg[*]]
set_false_path -from [get_cells filter2D_hls_CONTROL_BUS_s_axi_U/int_mode_reg[*]]
set_false_path -from [get_cells filter2D_hls_CONTROL_BUS_s_axi_U/int_r1_V_reg[*]]
set_false_path -from [get_cells filter2D_hls_CONTROL_BUS_s_axi_U/int_r2_V_reg[*]]
set_false_path -from [get_cells filter2D_hls_CONTROL_BUS_s_axi_U/int_r3_V_reg[*]]
