# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/sdi_admin/CloudStation/HLS/filter2D_f/solution1/impl/verilog/project.cache/wt [current_project]
set_property parent.project_path C:/Users/sdi_admin/CloudStation/HLS/filter2D_f/solution1/impl/verilog/project.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/sdi_admin/CloudStation/HLS/filter2D_f/solution1/impl/verilog/Block_Mat_exit65294_s.v
  C:/Users/sdi_admin/CloudStation/HLS/filter2D_f/solution1/impl/verilog/Block_proc_filter2D_f.v
  C:/Users/sdi_admin/CloudStation/HLS/filter2D_f/solution1/impl/verilog/Filter2D_filter2D_f.v
  C:/Users/sdi_admin/CloudStation/HLS/filter2D_f/solution1/impl/verilog/Filter2D_k_buf_0_dEe.v
  C:/Users/sdi_admin/CloudStation/HLS/filter2D_f/solution1/impl/verilog/Loop_1_proc_filter2D_f.v
  C:/Users/sdi_admin/CloudStation/HLS/filter2D_f/solution1/impl/verilog/Loop_2_proc_filter2D_f.v
  C:/Users/sdi_admin/CloudStation/HLS/filter2D_f/solution1/impl/verilog/fifo_w25_d2_A.v
  C:/Users/sdi_admin/CloudStation/HLS/filter2D_f/solution1/impl/verilog/fifo_w32_d2_A.v
  C:/Users/sdi_admin/CloudStation/HLS/filter2D_f/solution1/impl/verilog/fifo_w32_d3_A.v
  C:/Users/sdi_admin/CloudStation/HLS/filter2D_f/solution1/impl/verilog/fifo_w8_d1_A.v
  C:/Users/sdi_admin/CloudStation/HLS/filter2D_f/solution1/impl/verilog/filter2D_f.v
  C:/Users/sdi_admin/CloudStation/HLS/filter2D_f/solution1/impl/verilog/filter2D_f_CONTROL_BUS_s_axi.v
  C:/Users/sdi_admin/CloudStation/HLS/filter2D_f/solution1/impl/verilog/filter2D_f_mac_muibs.v
  C:/Users/sdi_admin/CloudStation/HLS/filter2D_f/solution1/impl/verilog/filter2D_f_mac_mujbC.v
  C:/Users/sdi_admin/CloudStation/HLS/filter2D_f/solution1/impl/verilog/filter2D_f_mac_mukbM.v
  C:/Users/sdi_admin/CloudStation/HLS/filter2D_f/solution1/impl/verilog/filter2D_f_mac_mulbW.v
  C:/Users/sdi_admin/CloudStation/HLS/filter2D_f/solution1/impl/verilog/filter2D_f_mul_32bkb.v
  C:/Users/sdi_admin/CloudStation/HLS/filter2D_f/solution1/impl/verilog/filter2D_f_mul_32cud.v
  C:/Users/sdi_admin/CloudStation/HLS/filter2D_f/solution1/impl/verilog/filter2D_f_mul_32mb6.v
  C:/Users/sdi_admin/CloudStation/HLS/filter2D_f/solution1/impl/verilog/filter2D_f_mul_muhbi.v
  C:/Users/sdi_admin/CloudStation/HLS/filter2D_f/solution1/impl/verilog/filter2D_f_mux_32g8j.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/sdi_admin/CloudStation/HLS/filter2D_f/solution1/impl/verilog/filter2D_f.xdc
set_property used_in_implementation false [get_files C:/Users/sdi_admin/CloudStation/HLS/filter2D_f/solution1/impl/verilog/filter2D_f.xdc]


synth_design -top filter2D_f -part xc7z020clg400-1 -no_iobuf -mode out_of_context


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef filter2D_f.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file filter2D_f_utilization_synth.rpt -pb filter2D_f_utilization_synth.pb"
