// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Filter2D_filter2D_f (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_src_rows_V,
        p_src_cols_V,
        p_src_data_stream_V_dout,
        p_src_data_stream_V_empty_n,
        p_src_data_stream_V_read,
        p_dst_data_stream_V_din,
        p_dst_data_stream_V_full_n,
        p_dst_data_stream_V_write,
        p_kernel_val_0_V_0_dout,
        p_kernel_val_0_V_0_empty_n,
        p_kernel_val_0_V_0_read,
        p_kernel_val_0_V_1_dout,
        p_kernel_val_0_V_1_empty_n,
        p_kernel_val_0_V_1_read,
        p_kernel_val_0_V_2_dout,
        p_kernel_val_0_V_2_empty_n,
        p_kernel_val_0_V_2_read,
        p_kernel_val_1_V_0_dout,
        p_kernel_val_1_V_0_empty_n,
        p_kernel_val_1_V_0_read,
        p_kernel_val_1_V_1_dout,
        p_kernel_val_1_V_1_empty_n,
        p_kernel_val_1_V_1_read,
        p_kernel_val_1_V_2_dout,
        p_kernel_val_1_V_2_empty_n,
        p_kernel_val_1_V_2_read,
        p_kernel_val_2_V_0_dout,
        p_kernel_val_2_V_0_empty_n,
        p_kernel_val_2_V_0_read,
        p_kernel_val_2_V_1_dout,
        p_kernel_val_2_V_1_empty_n,
        p_kernel_val_2_V_1_read,
        p_kernel_val_2_V_2_dout,
        p_kernel_val_2_V_2_empty_n,
        p_kernel_val_2_V_2_read
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_pp0_stage0 = 6'd16;
parameter    ap_ST_fsm_state20 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] p_src_rows_V;
input  [31:0] p_src_cols_V;
input  [7:0] p_src_data_stream_V_dout;
input   p_src_data_stream_V_empty_n;
output   p_src_data_stream_V_read;
output  [7:0] p_dst_data_stream_V_din;
input   p_dst_data_stream_V_full_n;
output   p_dst_data_stream_V_write;
input  [24:0] p_kernel_val_0_V_0_dout;
input   p_kernel_val_0_V_0_empty_n;
output   p_kernel_val_0_V_0_read;
input  [24:0] p_kernel_val_0_V_1_dout;
input   p_kernel_val_0_V_1_empty_n;
output   p_kernel_val_0_V_1_read;
input  [24:0] p_kernel_val_0_V_2_dout;
input   p_kernel_val_0_V_2_empty_n;
output   p_kernel_val_0_V_2_read;
input  [24:0] p_kernel_val_1_V_0_dout;
input   p_kernel_val_1_V_0_empty_n;
output   p_kernel_val_1_V_0_read;
input  [24:0] p_kernel_val_1_V_1_dout;
input   p_kernel_val_1_V_1_empty_n;
output   p_kernel_val_1_V_1_read;
input  [24:0] p_kernel_val_1_V_2_dout;
input   p_kernel_val_1_V_2_empty_n;
output   p_kernel_val_1_V_2_read;
input  [24:0] p_kernel_val_2_V_0_dout;
input   p_kernel_val_2_V_0_empty_n;
output   p_kernel_val_2_V_0_read;
input  [24:0] p_kernel_val_2_V_1_dout;
input   p_kernel_val_2_V_1_empty_n;
output   p_kernel_val_2_V_1_read;
input  [24:0] p_kernel_val_2_V_2_dout;
input   p_kernel_val_2_V_2_empty_n;
output   p_kernel_val_2_V_2_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_V_read;
reg p_dst_data_stream_V_write;
reg p_kernel_val_0_V_0_read;
reg p_kernel_val_0_V_1_read;
reg p_kernel_val_0_V_2_read;
reg p_kernel_val_1_V_0_read;
reg p_kernel_val_1_V_1_read;
reg p_kernel_val_1_V_2_read;
reg p_kernel_val_2_V_0_read;
reg p_kernel_val_2_V_1_read;
reg p_kernel_val_2_V_2_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    p_src_data_stream_V_blk_n;
reg    ap_enable_reg_pp0_iter2;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond388_i_i_reg_1950;
reg   [0:0] ap_reg_pp0_iter1_exitcond388_i_i_reg_1950;
reg   [0:0] or_cond_i_i_i_reg_1981;
reg   [0:0] icmp_reg_1841;
reg   [0:0] tmp_2_i_reg_1832;
reg    p_dst_data_stream_V_blk_n;
reg    ap_enable_reg_pp0_iter14;
reg   [0:0] or_cond_i_i_reg_1977;
reg   [0:0] ap_reg_pp0_iter13_or_cond_i_i_reg_1977;
reg    p_kernel_val_0_V_0_blk_n;
reg    p_kernel_val_0_V_1_blk_n;
reg    p_kernel_val_0_V_2_blk_n;
reg    p_kernel_val_1_V_0_blk_n;
reg    p_kernel_val_1_V_1_blk_n;
reg    p_kernel_val_1_V_2_blk_n;
reg    p_kernel_val_2_V_0_blk_n;
reg    p_kernel_val_2_V_1_blk_n;
reg    p_kernel_val_2_V_2_blk_n;
reg   [10:0] t_V_1_reg_500;
reg   [7:0] reg_511;
wire    ap_block_state5_pp0_stage0_iter0;
wire    ap_block_state6_pp0_stage0_iter1;
reg    ap_predicate_op204_read_state7;
reg    ap_predicate_op205_read_state7;
reg    ap_block_state7_pp0_stage0_iter2;
wire    ap_block_state8_pp0_stage0_iter3;
wire    ap_block_state9_pp0_stage0_iter4;
wire    ap_block_state10_pp0_stage0_iter5;
wire    ap_block_state11_pp0_stage0_iter6;
wire    ap_block_state12_pp0_stage0_iter7;
wire    ap_block_state13_pp0_stage0_iter8;
wire    ap_block_state14_pp0_stage0_iter9;
wire    ap_block_state15_pp0_stage0_iter10;
wire    ap_block_state16_pp0_stage0_iter11;
wire    ap_block_state17_pp0_stage0_iter12;
wire    ap_block_state18_pp0_stage0_iter13;
reg    ap_block_state19_pp0_stage0_iter14;
reg    ap_block_pp0_stage0_11001;
reg   [7:0] ap_reg_pp0_iter3_reg_511;
wire   [11:0] tmp_9_fu_518_p1;
reg    ap_block_state1;
wire   [10:0] tmp_11_fu_522_p1;
wire   [11:0] tmp_16_fu_526_p1;
wire   [10:0] tmp_i_fu_534_p2;
wire   [10:0] tmp_1_i_fu_540_p2;
wire   [1:0] tmp_23_fu_550_p1;
wire   [12:0] tmp_135_cast_cast_i_fu_572_p1;
wire   [1:0] tmp_fu_576_p2;
wire  signed [32:0] OP2_V_0_i_fu_594_p1;
reg  signed [32:0] OP2_V_0_i_reg_1763;
wire  signed [32:0] OP2_V_0_1_i_fu_598_p1;
reg  signed [32:0] OP2_V_0_1_i_reg_1768;
wire  signed [32:0] OP2_V_0_2_i_fu_602_p1;
reg  signed [32:0] OP2_V_0_2_i_reg_1773;
wire  signed [32:0] OP2_V_1_i_fu_606_p1;
reg  signed [32:0] OP2_V_1_i_reg_1778;
wire  signed [32:0] OP2_V_1_1_i_fu_610_p1;
reg  signed [32:0] OP2_V_1_1_i_reg_1783;
wire  signed [32:0] OP2_V_1_2_i_fu_614_p1;
reg  signed [32:0] OP2_V_1_2_i_reg_1788;
wire  signed [32:0] OP2_V_2_i_fu_618_p1;
reg  signed [32:0] OP2_V_2_i_reg_1793;
wire  signed [32:0] OP2_V_2_1_i_fu_622_p1;
reg  signed [32:0] OP2_V_2_1_i_reg_1798;
wire  signed [32:0] OP2_V_2_2_i_fu_626_p1;
reg  signed [32:0] OP2_V_2_2_i_reg_1803;
wire   [12:0] tmp_10_cast_cast_i_fu_644_p1;
wire   [1:0] tmp_5_fu_648_p2;
wire   [1:0] tmp_s_fu_654_p2;
wire   [10:0] i_V_fu_669_p2;
reg   [10:0] i_V_reg_1827;
wire    ap_CS_fsm_state2;
wire   [0:0] tmp_2_i_fu_675_p2;
wire   [0:0] exitcond389_i_i_fu_664_p2;
wire   [0:0] ult_fu_680_p2;
reg   [0:0] ult_reg_1836;
wire   [0:0] icmp_fu_695_p2;
wire   [0:0] tmp_93_i_fu_701_p2;
reg   [0:0] tmp_93_i_reg_1846;
wire   [0:0] tmp_93_1_i_fu_707_p2;
reg   [0:0] tmp_93_1_i_reg_1850;
wire   [0:0] tmp_115_i_fu_713_p2;
reg   [0:0] tmp_115_i_reg_1854;
wire   [11:0] tmp_118_i_fu_718_p2;
reg   [11:0] tmp_118_i_reg_1861;
reg   [0:0] tmp_30_reg_1869;
wire   [11:0] p_assign_7_i_fu_732_p2;
reg   [11:0] p_assign_7_i_reg_1874;
wire   [11:0] p_assign_6_1_i_fu_738_p2;
reg   [11:0] p_assign_6_1_i_reg_1879;
reg   [0:0] tmp_32_reg_1887;
wire   [11:0] p_assign_7_1_i_fu_752_p2;
reg   [11:0] p_assign_7_1_i_reg_1892;
wire   [11:0] p_assign_6_2_i_fu_758_p2;
reg   [11:0] p_assign_6_2_i_reg_1897;
reg   [0:0] tmp_35_reg_1905;
wire   [11:0] p_assign_7_2_i_fu_772_p2;
reg   [11:0] p_assign_7_2_i_reg_1910;
wire   [1:0] tmp_42_fu_913_p3;
reg   [1:0] tmp_42_reg_1915;
wire    ap_CS_fsm_state3;
wire   [1:0] tmp_3_fu_937_p3;
reg   [1:0] tmp_3_reg_1920;
wire   [1:0] tmp_7_fu_961_p3;
reg   [1:0] tmp_7_reg_1925;
wire   [0:0] rev_fu_969_p2;
reg   [0:0] rev_reg_1930;
wire    ap_CS_fsm_state4;
wire   [1:0] tmp_43_fu_979_p2;
reg   [1:0] tmp_43_reg_1935;
wire   [1:0] row_assign_8_1_t_i_fu_984_p2;
reg   [1:0] row_assign_8_1_t_i_reg_1940;
wire   [1:0] row_assign_8_2_t_i_fu_988_p2;
reg   [1:0] row_assign_8_2_t_i_reg_1945;
wire   [0:0] exitcond388_i_i_fu_996_p2;
wire    ap_CS_fsm_pp0_stage0;
reg   [0:0] ap_reg_pp0_iter2_exitcond388_i_i_reg_1950;
reg   [0:0] ap_reg_pp0_iter3_exitcond388_i_i_reg_1950;
reg   [0:0] ap_reg_pp0_iter4_exitcond388_i_i_reg_1950;
reg   [0:0] ap_reg_pp0_iter5_exitcond388_i_i_reg_1950;
wire   [10:0] j_V_fu_1001_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [11:0] ImagLoc_x_fu_1023_p2;
reg   [11:0] ImagLoc_x_reg_1959;
reg   [0:0] tmp_47_reg_1965;
wire   [11:0] p_p2_i_i_i_fu_1051_p3;
reg   [11:0] p_p2_i_i_i_reg_1971;
wire   [0:0] or_cond_i_i_fu_1059_p2;
reg   [0:0] ap_reg_pp0_iter1_or_cond_i_i_reg_1977;
reg   [0:0] ap_reg_pp0_iter2_or_cond_i_i_reg_1977;
reg   [0:0] ap_reg_pp0_iter3_or_cond_i_i_reg_1977;
reg   [0:0] ap_reg_pp0_iter4_or_cond_i_i_reg_1977;
reg   [0:0] ap_reg_pp0_iter5_or_cond_i_i_reg_1977;
reg   [0:0] ap_reg_pp0_iter6_or_cond_i_i_reg_1977;
reg   [0:0] ap_reg_pp0_iter7_or_cond_i_i_reg_1977;
reg   [0:0] ap_reg_pp0_iter8_or_cond_i_i_reg_1977;
reg   [0:0] ap_reg_pp0_iter9_or_cond_i_i_reg_1977;
reg   [0:0] ap_reg_pp0_iter10_or_cond_i_i_reg_1977;
reg   [0:0] ap_reg_pp0_iter11_or_cond_i_i_reg_1977;
reg   [0:0] ap_reg_pp0_iter12_or_cond_i_i_reg_1977;
wire   [0:0] or_cond_i_i_i_fu_1076_p2;
reg   [0:0] ap_reg_pp0_iter2_or_cond_i_i_i_reg_1981;
reg   [0:0] ap_reg_pp0_iter3_or_cond_i_i_i_reg_1981;
wire   [12:0] x_fu_1119_p3;
reg   [12:0] x_reg_1985;
wire   [1:0] tmp_49_fu_1127_p1;
reg   [1:0] tmp_49_reg_1990;
wire   [0:0] brmerge_i_fu_1131_p2;
reg   [0:0] brmerge_i_reg_1995;
reg   [0:0] ap_reg_pp0_iter2_brmerge_i_reg_1995;
reg   [10:0] k_buf_0_val_3_addr_reg_2002;
wire   [1:0] col_assign_1_t_i_fu_1146_p2;
reg   [1:0] col_assign_1_t_i_reg_2008;
reg   [10:0] k_buf_0_val_4_addr_reg_2015;
reg   [10:0] ap_reg_pp0_iter3_k_buf_0_val_4_addr_reg_2015;
reg   [10:0] k_buf_0_val_5_addr_reg_2021;
reg   [10:0] ap_reg_pp0_iter3_k_buf_0_val_5_addr_reg_2021;
wire   [7:0] k_buf_0_val_3_q0;
reg   [7:0] k_buf_0_val_3_load_reg_2027;
reg    ap_enable_reg_pp0_iter3;
wire   [7:0] col_buf_0_val_0_0_fu_1179_p3;
reg   [7:0] col_buf_0_val_0_0_reg_2032;
wire   [7:0] k_buf_0_val_4_q0;
reg   [7:0] k_buf_0_val_4_load_reg_2040;
wire   [7:0] col_buf_0_val_1_0_fu_1197_p3;
reg   [7:0] col_buf_0_val_1_0_reg_2045;
wire   [7:0] col_buf_0_val_2_0_fu_1215_p3;
reg   [7:0] col_buf_0_val_2_0_reg_2053;
wire   [7:0] src_kernel_win_0_va_6_fu_1266_p3;
reg   [7:0] src_kernel_win_0_va_6_reg_2061;
reg   [7:0] ap_reg_pp0_iter5_src_kernel_win_0_va_6_reg_2061;
reg   [7:0] ap_reg_pp0_iter6_src_kernel_win_0_va_6_reg_2061;
reg   [7:0] ap_reg_pp0_iter7_src_kernel_win_0_va_6_reg_2061;
reg   [7:0] ap_reg_pp0_iter8_src_kernel_win_0_va_6_reg_2061;
reg   [7:0] ap_reg_pp0_iter9_src_kernel_win_0_va_6_reg_2061;
wire   [7:0] src_kernel_win_0_va_7_fu_1280_p3;
reg   [7:0] src_kernel_win_0_va_7_reg_2067;
reg   [7:0] ap_reg_pp0_iter5_src_kernel_win_0_va_7_reg_2067;
reg   [7:0] ap_reg_pp0_iter6_src_kernel_win_0_va_7_reg_2067;
reg   [7:0] ap_reg_pp0_iter7_src_kernel_win_0_va_7_reg_2067;
wire   [7:0] src_kernel_win_0_va_8_fu_1294_p3;
reg   [7:0] src_kernel_win_0_va_8_reg_2073;
reg   [7:0] src_kernel_win_0_va_17_reg_2089;
reg   [7:0] src_kernel_win_0_va_9_reg_2094;
reg   [7:0] src_kernel_win_0_va_11_reg_2099;
reg   [7:0] ap_reg_pp0_iter7_src_kernel_win_0_va_11_reg_2099;
wire  signed [32:0] grp_fu_1576_p2;
reg  signed [32:0] r_V_2_0_1_i_reg_2119;
wire  signed [32:0] grp_fu_1581_p2;
reg  signed [32:0] r_V_2_0_2_i_reg_2124;
wire  signed [33:0] grp_fu_1586_p3;
reg  signed [33:0] p_Val2_5_0_1_i_reg_2134;
reg    ap_enable_reg_pp0_iter8;
wire  signed [33:0] grp_fu_1593_p3;
reg  signed [33:0] tmp24_reg_2139;
wire  signed [32:0] grp_fu_1600_p2;
reg  signed [32:0] r_V_2_2_i_reg_2154;
wire   [34:0] p_Val2_5_1_i_fu_1393_p2;
reg  signed [34:0] p_Val2_5_1_i_reg_2159;
wire  signed [33:0] grp_fu_1605_p3;
reg  signed [33:0] tmp27_reg_2164;
reg    ap_enable_reg_pp0_iter9;
wire  signed [35:0] grp_fu_1612_p3;
reg  signed [35:0] tmp25_reg_2169;
reg    ap_enable_reg_pp0_iter10;
wire  signed [34:0] grp_fu_1619_p3;
reg  signed [34:0] tmp26_reg_2174;
(* use_dsp48 = "no" *) wire   [35:0] p_Val2_5_2_1_i_fu_1414_p2;
reg  signed [35:0] p_Val2_5_2_1_i_reg_2184;
wire  signed [36:0] grp_fu_1626_p3;
reg  signed [36:0] p_Val2_3_reg_2189;
reg    ap_enable_reg_pp0_iter12;
reg   [0:0] signbit_reg_2194;
reg   [7:0] p_Val2_1_reg_2201;
reg   [0:0] tmp_53_reg_2206;
wire   [0:0] Range1_all_ones_fu_1454_p2;
reg   [0:0] Range1_all_ones_reg_2211;
wire   [0:0] Range1_all_zeros_fu_1460_p2;
reg   [0:0] Range1_all_zeros_reg_2217;
wire   [7:0] p_Val2_2_fu_1476_p2;
reg   [7:0] p_Val2_2_reg_2222;
wire   [0:0] p_39_demorgan_i_i_i_i_fu_1523_p2;
reg   [0:0] p_39_demorgan_i_i_i_i_reg_2227;
wire   [0:0] neg_src_not_i_i_i_fu_1533_p2;
reg   [0:0] neg_src_not_i_i_i_reg_2233;
wire   [7:0] p_i_i_i_fu_1539_p3;
reg   [7:0] p_i_i_i_reg_2239;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter4;
reg    ap_condition_pp0_exit_iter3_state8;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter13;
wire   [10:0] k_buf_0_val_3_address0;
reg    k_buf_0_val_3_ce0;
reg    k_buf_0_val_3_ce1;
reg    k_buf_0_val_3_we1;
wire   [10:0] k_buf_0_val_4_address0;
reg    k_buf_0_val_4_ce0;
reg    k_buf_0_val_4_ce1;
reg    k_buf_0_val_4_we1;
reg   [7:0] k_buf_0_val_4_d1;
wire   [10:0] k_buf_0_val_5_address0;
reg    k_buf_0_val_5_ce0;
wire   [7:0] k_buf_0_val_5_q0;
reg    k_buf_0_val_5_ce1;
reg    k_buf_0_val_5_we1;
reg   [7:0] k_buf_0_val_5_d1;
reg   [10:0] t_V_reg_489;
wire    ap_CS_fsm_state20;
wire   [63:0] tmp_58_i_fu_1139_p1;
reg    ap_block_pp0_stage0_01001;
reg   [7:0] src_kernel_win_0_va_fu_308;
reg   [7:0] src_kernel_win_0_va_1_fu_312;
reg   [7:0] src_kernel_win_0_va_2_fu_316;
reg   [7:0] src_kernel_win_0_va_3_fu_320;
reg   [7:0] src_kernel_win_0_va_4_fu_324;
reg   [7:0] src_kernel_win_0_va_5_fu_328;
reg   [7:0] right_border_buf_0_s_fu_332;
reg   [7:0] right_border_buf_0_1_fu_336;
reg   [7:0] right_border_buf_0_2_fu_340;
reg   [7:0] right_border_buf_0_3_fu_344;
reg   [7:0] right_border_buf_0_4_fu_348;
reg   [7:0] right_border_buf_0_5_fu_352;
wire   [10:0] tmp_17_fu_530_p1;
wire   [11:0] tmp_134_i_fu_558_p3;
wire   [11:0] tmp_135_i_fu_566_p2;
wire   [1:0] tmp_22_fu_546_p1;
wire   [0:0] tmp_27_fu_582_p1;
wire   [11:0] tmp_9_i_fu_630_p3;
wire   [11:0] tmp_10_i_fu_638_p2;
wire   [1:0] tmp_1_fu_586_p3;
wire   [1:0] tmp_26_fu_554_p1;
wire   [9:0] tmp_28_fu_685_p4;
wire   [11:0] t_V_cast_i_fu_660_p1;
wire   [0:0] tmp_29_fu_778_p3;
wire   [0:0] tmp_120_i_fu_791_p2;
wire   [0:0] rev1_fu_785_p2;
wire   [11:0] p_p2_i425_i_i_fu_801_p3;
wire  signed [12:0] p_p2_i425_i_cast_cast_fu_806_p1;
wire   [0:0] tmp_31_fu_820_p3;
wire   [0:0] tmp_120_1_i_fu_833_p2;
wire   [0:0] rev2_fu_827_p2;
wire   [11:0] p_p2_i425_i_1_i_fu_843_p3;
wire   [0:0] tmp_34_fu_857_p3;
wire   [0:0] tmp_120_2_i_fu_870_p2;
wire   [0:0] rev3_fu_864_p2;
wire   [11:0] p_p2_i425_i_2_i_fu_880_p3;
wire   [12:0] p_assign_8_i_fu_815_p2;
wire   [0:0] tmp_132_i_fu_810_p2;
wire   [1:0] tmp_39_fu_897_p1;
wire   [1:0] tmp_40_fu_901_p1;
wire   [0:0] or_cond_i424_i_i_fu_795_p2;
wire   [1:0] tmp_38_fu_894_p1;
wire   [1:0] tmp_41_fu_905_p3;
wire   [1:0] tmp_33_fu_853_p1;
wire   [0:0] tmp_132_1_i_fu_848_p2;
wire   [1:0] tmp_8_fu_921_p2;
wire   [0:0] or_cond_i424_i_1_i_fu_837_p2;
wire   [1:0] tmp_44_fu_934_p1;
wire   [1:0] tmp_2_fu_926_p3;
wire   [1:0] tmp_36_fu_890_p1;
wire   [0:0] tmp_132_2_i_fu_885_p2;
wire   [1:0] tmp_4_fu_945_p2;
wire   [0:0] or_cond_i424_i_2_i_fu_874_p2;
wire   [1:0] tmp_45_fu_958_p1;
wire   [1:0] tmp_6_fu_950_p3;
wire   [1:0] tmp_37_fu_974_p2;
wire   [9:0] tmp_46_fu_1007_p4;
wire   [11:0] t_V_1_cast_i_fu_992_p1;
wire   [0:0] tmp_48_fu_1037_p3;
wire   [11:0] p_assign_1_fu_1045_p2;
wire   [0:0] icmp1_fu_1017_p2;
wire   [0:0] tmp_6_i_fu_1072_p2;
wire   [0:0] rev4_fu_1067_p2;
wire  signed [12:0] p_p2_i_i_cast_cast19_s_fu_1082_p1;
wire  signed [12:0] ImagLoc_x_cast_cast_s_fu_1064_p1;
wire   [12:0] p_assign_2_fu_1089_p2;
wire   [0:0] tmp_6_i_not_fu_1102_p2;
wire   [0:0] tmp_8_i_fu_1085_p2;
wire   [0:0] sel_tmp7_fu_1108_p2;
wire   [0:0] sel_tmp8_fu_1113_p2;
wire   [12:0] sel_tmp_fu_1094_p3;
wire  signed [31:0] col_assign_cast_i_fu_1136_p1;
wire   [7:0] tmp_10_fu_1168_p5;
wire   [7:0] tmp_12_fu_1186_p5;
wire   [7:0] tmp_13_fu_1204_p5;
wire   [7:0] tmp_14_fu_1258_p5;
wire   [7:0] tmp_15_fu_1272_p5;
wire   [7:0] tmp_18_fu_1286_p5;
wire  signed [34:0] tmp24_cast_fu_1390_p1;
wire  signed [34:0] p_Val2_5_0_1_cast_s_fu_1387_p1;
wire  signed [35:0] tmp26_cast_fu_1411_p1;
wire   [5:0] p_Result_6_i_i_i_fu_1445_p4;
wire   [7:0] tmp_3_i_i_i_fu_1466_p1;
wire   [0:0] tmp_55_fu_1481_p3;
wire   [0:0] tmp_54_fu_1469_p3;
wire   [0:0] tmp_8_i_i_i_fu_1489_p2;
wire   [0:0] carry_fu_1495_p2;
wire   [0:0] p_38_i_i_i_i_fu_1507_p2;
wire   [0:0] tmp_i_i_i_fu_1512_p2;
wire   [0:0] deleted_zeros_fu_1501_p3;
wire   [0:0] signbit_not_fu_1528_p2;
wire   [0:0] neg_src_fu_1518_p2;
wire   [0:0] p_39_demorgan_i_not_i_fu_1551_p2;
wire   [0:0] brmerge_i_i_not_i_i_s_fu_1547_p2;
wire   [0:0] brmerge_i_i_i_fu_1556_p2;
wire   [7:0] p_mux_i_i_i_fu_1561_p3;
wire  signed [24:0] grp_fu_1576_p0;
wire   [7:0] grp_fu_1576_p1;
wire  signed [24:0] grp_fu_1581_p0;
wire   [7:0] grp_fu_1581_p1;
wire  signed [24:0] grp_fu_1586_p0;
wire   [7:0] grp_fu_1586_p1;
wire  signed [24:0] grp_fu_1593_p0;
wire   [7:0] grp_fu_1593_p1;
wire  signed [24:0] grp_fu_1600_p0;
wire   [7:0] grp_fu_1600_p1;
wire  signed [24:0] grp_fu_1605_p0;
wire   [7:0] grp_fu_1605_p1;
wire  signed [24:0] grp_fu_1612_p0;
wire   [7:0] grp_fu_1612_p1;
wire  signed [24:0] grp_fu_1619_p0;
wire   [7:0] grp_fu_1619_p1;
wire  signed [24:0] grp_fu_1626_p0;
wire   [7:0] grp_fu_1626_p1;
reg    grp_fu_1576_ce;
reg    grp_fu_1581_ce;
reg    grp_fu_1586_ce;
reg    grp_fu_1593_ce;
reg    grp_fu_1600_ce;
reg    grp_fu_1605_ce;
reg    grp_fu_1612_ce;
reg    grp_fu_1619_ce;
reg    grp_fu_1626_ce;
reg   [5:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [32:0] grp_fu_1576_p10;
wire   [32:0] grp_fu_1581_p10;
wire   [32:0] grp_fu_1586_p10;
wire   [32:0] grp_fu_1593_p10;
wire   [32:0] grp_fu_1600_p10;
wire   [32:0] grp_fu_1605_p10;
wire   [32:0] grp_fu_1612_p10;
wire   [32:0] grp_fu_1619_p10;
wire   [32:0] grp_fu_1626_p10;
reg    ap_condition_1475;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 6'd1;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
end

Filter2D_k_buf_0_dEe #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_3_address0),
    .ce0(k_buf_0_val_3_ce0),
    .q0(k_buf_0_val_3_q0),
    .address1(k_buf_0_val_3_addr_reg_2002),
    .ce1(k_buf_0_val_3_ce1),
    .we1(k_buf_0_val_3_we1),
    .d1(reg_511)
);

Filter2D_k_buf_0_dEe #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_4_address0),
    .ce0(k_buf_0_val_4_ce0),
    .q0(k_buf_0_val_4_q0),
    .address1(ap_reg_pp0_iter3_k_buf_0_val_4_addr_reg_2015),
    .ce1(k_buf_0_val_4_ce1),
    .we1(k_buf_0_val_4_we1),
    .d1(k_buf_0_val_4_d1)
);

Filter2D_k_buf_0_dEe #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_5_address0),
    .ce0(k_buf_0_val_5_ce0),
    .q0(k_buf_0_val_5_q0),
    .address1(ap_reg_pp0_iter3_k_buf_0_val_5_addr_reg_2021),
    .ce1(k_buf_0_val_5_ce1),
    .we1(k_buf_0_val_5_we1),
    .d1(k_buf_0_val_5_d1)
);

filter2D_f_mux_32g8j #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
filter2D_f_mux_32g8j_U31(
    .din0(right_border_buf_0_s_fu_332),
    .din1(right_border_buf_0_1_fu_336),
    .din2(8'd0),
    .din3(col_assign_1_t_i_reg_2008),
    .dout(tmp_10_fu_1168_p5)
);

filter2D_f_mux_32g8j #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
filter2D_f_mux_32g8j_U32(
    .din0(right_border_buf_0_3_fu_344),
    .din1(right_border_buf_0_4_fu_348),
    .din2(8'd0),
    .din3(col_assign_1_t_i_reg_2008),
    .dout(tmp_12_fu_1186_p5)
);

filter2D_f_mux_32g8j #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
filter2D_f_mux_32g8j_U33(
    .din0(right_border_buf_0_5_fu_352),
    .din1(right_border_buf_0_2_fu_340),
    .din2(8'd0),
    .din3(col_assign_1_t_i_reg_2008),
    .dout(tmp_13_fu_1204_p5)
);

filter2D_f_mux_32g8j #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
filter2D_f_mux_32g8j_U34(
    .din0(col_buf_0_val_0_0_reg_2032),
    .din1(col_buf_0_val_1_0_reg_2045),
    .din2(col_buf_0_val_2_0_reg_2053),
    .din3(tmp_43_reg_1935),
    .dout(tmp_14_fu_1258_p5)
);

filter2D_f_mux_32g8j #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
filter2D_f_mux_32g8j_U35(
    .din0(col_buf_0_val_0_0_reg_2032),
    .din1(col_buf_0_val_1_0_reg_2045),
    .din2(col_buf_0_val_2_0_reg_2053),
    .din3(row_assign_8_1_t_i_reg_1940),
    .dout(tmp_15_fu_1272_p5)
);

filter2D_f_mux_32g8j #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
filter2D_f_mux_32g8j_U36(
    .din0(col_buf_0_val_0_0_reg_2032),
    .din1(col_buf_0_val_1_0_reg_2045),
    .din2(col_buf_0_val_2_0_reg_2053),
    .din3(row_assign_8_2_t_i_reg_1945),
    .dout(tmp_18_fu_1286_p5)
);

filter2D_f_mul_muhbi #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 25 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 33 ))
filter2D_f_mul_muhbi_U37(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1576_p0),
    .din1(grp_fu_1576_p1),
    .ce(grp_fu_1576_ce),
    .dout(grp_fu_1576_p2)
);

filter2D_f_mul_muhbi #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 25 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 33 ))
filter2D_f_mul_muhbi_U38(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1581_p0),
    .din1(grp_fu_1581_p1),
    .ce(grp_fu_1581_ce),
    .dout(grp_fu_1581_p2)
);

filter2D_f_mac_muibs #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 25 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 34 ))
filter2D_f_mac_muibs_U39(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1586_p0),
    .din1(grp_fu_1586_p1),
    .din2(r_V_2_0_1_i_reg_2119),
    .ce(grp_fu_1586_ce),
    .dout(grp_fu_1586_p3)
);

filter2D_f_mac_muibs #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 25 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 34 ))
filter2D_f_mac_muibs_U40(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1593_p0),
    .din1(grp_fu_1593_p1),
    .din2(r_V_2_0_2_i_reg_2124),
    .ce(grp_fu_1593_ce),
    .dout(grp_fu_1593_p3)
);

filter2D_f_mul_muhbi #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 25 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 33 ))
filter2D_f_mul_muhbi_U41(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1600_p0),
    .din1(grp_fu_1600_p1),
    .ce(grp_fu_1600_ce),
    .dout(grp_fu_1600_p2)
);

filter2D_f_mac_muibs #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 25 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 34 ))
filter2D_f_mac_muibs_U42(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1605_p0),
    .din1(grp_fu_1605_p1),
    .din2(r_V_2_2_i_reg_2154),
    .ce(grp_fu_1605_ce),
    .dout(grp_fu_1605_p3)
);

filter2D_f_mac_mujbC #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 25 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 35 ),
    .dout_WIDTH( 36 ))
filter2D_f_mac_mujbC_U43(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1612_p0),
    .din1(grp_fu_1612_p1),
    .din2(p_Val2_5_1_i_reg_2159),
    .ce(grp_fu_1612_ce),
    .dout(grp_fu_1612_p3)
);

filter2D_f_mac_mukbM #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 25 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 34 ),
    .dout_WIDTH( 35 ))
filter2D_f_mac_mukbM_U44(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1619_p0),
    .din1(grp_fu_1619_p1),
    .din2(tmp27_reg_2164),
    .ce(grp_fu_1619_ce),
    .dout(grp_fu_1619_p3)
);

filter2D_f_mac_mulbW #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 25 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 37 ))
filter2D_f_mac_mulbW_U45(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1626_p0),
    .din1(grp_fu_1626_p1),
    .din2(p_Val2_5_2_1_i_reg_2184),
    .ce(grp_fu_1626_ce),
    .dout(grp_fu_1626_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((exitcond389_i_i_fu_664_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((exitcond388_i_i_fu_996_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_enable_reg_pp0_iter14 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter3_state8)) begin
                ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter2;
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond388_i_i_fu_996_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        t_V_1_reg_500 <= j_V_fu_1001_p2;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        t_V_1_reg_500 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        t_V_reg_489 <= i_V_reg_1827;
    end else if ((~((p_kernel_val_2_V_2_empty_n == 1'b0) | (p_kernel_val_2_V_1_empty_n == 1'b0) | (p_kernel_val_2_V_0_empty_n == 1'b0) | (p_kernel_val_1_V_2_empty_n == 1'b0) | (p_kernel_val_1_V_1_empty_n == 1'b0) | (p_kernel_val_1_V_0_empty_n == 1'b0) | (p_kernel_val_0_V_2_empty_n == 1'b0) | (p_kernel_val_0_V_1_empty_n == 1'b0) | (p_kernel_val_0_V_0_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        t_V_reg_489 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond388_i_i_fu_996_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ImagLoc_x_reg_1959 <= ImagLoc_x_fu_1023_p2;
        or_cond_i_i_reg_1977 <= or_cond_i_i_fu_1059_p2;
        p_p2_i_i_i_reg_1971 <= p_p2_i_i_i_fu_1051_p3;
        tmp_47_reg_1965 <= ImagLoc_x_fu_1023_p2[32'd11];
    end
end

always @ (posedge ap_clk) begin
    if ((~((p_kernel_val_2_V_2_empty_n == 1'b0) | (p_kernel_val_2_V_1_empty_n == 1'b0) | (p_kernel_val_2_V_0_empty_n == 1'b0) | (p_kernel_val_1_V_2_empty_n == 1'b0) | (p_kernel_val_1_V_1_empty_n == 1'b0) | (p_kernel_val_1_V_0_empty_n == 1'b0) | (p_kernel_val_0_V_2_empty_n == 1'b0) | (p_kernel_val_0_V_1_empty_n == 1'b0) | (p_kernel_val_0_V_0_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        OP2_V_0_1_i_reg_1768 <= OP2_V_0_1_i_fu_598_p1;
        OP2_V_0_2_i_reg_1773 <= OP2_V_0_2_i_fu_602_p1;
        OP2_V_0_i_reg_1763 <= OP2_V_0_i_fu_594_p1;
        OP2_V_1_1_i_reg_1783 <= OP2_V_1_1_i_fu_610_p1;
        OP2_V_1_2_i_reg_1788 <= OP2_V_1_2_i_fu_614_p1;
        OP2_V_1_i_reg_1778 <= OP2_V_1_i_fu_606_p1;
        OP2_V_2_1_i_reg_1798 <= OP2_V_2_1_i_fu_622_p1;
        OP2_V_2_2_i_reg_1803 <= OP2_V_2_2_i_fu_626_p1;
        OP2_V_2_i_reg_1793 <= OP2_V_2_i_fu_618_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_pp0_iter11_or_cond_i_i_reg_1977 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Range1_all_ones_reg_2211 <= Range1_all_ones_fu_1454_p2;
        Range1_all_zeros_reg_2217 <= Range1_all_zeros_fu_1460_p2;
        p_Val2_1_reg_2201 <= {{grp_fu_1626_p3[30:23]}};
        signbit_reg_2194 <= grp_fu_1626_p3[32'd36];
        tmp_53_reg_2206 <= grp_fu_1626_p3[32'd22];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_reg_pp0_iter10_or_cond_i_i_reg_1977 <= ap_reg_pp0_iter9_or_cond_i_i_reg_1977;
        ap_reg_pp0_iter11_or_cond_i_i_reg_1977 <= ap_reg_pp0_iter10_or_cond_i_i_reg_1977;
        ap_reg_pp0_iter12_or_cond_i_i_reg_1977 <= ap_reg_pp0_iter11_or_cond_i_i_reg_1977;
        ap_reg_pp0_iter13_or_cond_i_i_reg_1977 <= ap_reg_pp0_iter12_or_cond_i_i_reg_1977;
        ap_reg_pp0_iter2_brmerge_i_reg_1995 <= brmerge_i_reg_1995;
        ap_reg_pp0_iter2_exitcond388_i_i_reg_1950 <= ap_reg_pp0_iter1_exitcond388_i_i_reg_1950;
        ap_reg_pp0_iter2_or_cond_i_i_i_reg_1981 <= or_cond_i_i_i_reg_1981;
        ap_reg_pp0_iter2_or_cond_i_i_reg_1977 <= ap_reg_pp0_iter1_or_cond_i_i_reg_1977;
        ap_reg_pp0_iter3_exitcond388_i_i_reg_1950 <= ap_reg_pp0_iter2_exitcond388_i_i_reg_1950;
        ap_reg_pp0_iter3_k_buf_0_val_4_addr_reg_2015 <= k_buf_0_val_4_addr_reg_2015;
        ap_reg_pp0_iter3_k_buf_0_val_5_addr_reg_2021 <= k_buf_0_val_5_addr_reg_2021;
        ap_reg_pp0_iter3_or_cond_i_i_i_reg_1981 <= ap_reg_pp0_iter2_or_cond_i_i_i_reg_1981;
        ap_reg_pp0_iter3_or_cond_i_i_reg_1977 <= ap_reg_pp0_iter2_or_cond_i_i_reg_1977;
        ap_reg_pp0_iter3_reg_511 <= reg_511;
        ap_reg_pp0_iter4_exitcond388_i_i_reg_1950 <= ap_reg_pp0_iter3_exitcond388_i_i_reg_1950;
        ap_reg_pp0_iter4_or_cond_i_i_reg_1977 <= ap_reg_pp0_iter3_or_cond_i_i_reg_1977;
        ap_reg_pp0_iter5_exitcond388_i_i_reg_1950 <= ap_reg_pp0_iter4_exitcond388_i_i_reg_1950;
        ap_reg_pp0_iter5_or_cond_i_i_reg_1977 <= ap_reg_pp0_iter4_or_cond_i_i_reg_1977;
        ap_reg_pp0_iter5_src_kernel_win_0_va_6_reg_2061 <= src_kernel_win_0_va_6_reg_2061;
        ap_reg_pp0_iter5_src_kernel_win_0_va_7_reg_2067 <= src_kernel_win_0_va_7_reg_2067;
        ap_reg_pp0_iter6_or_cond_i_i_reg_1977 <= ap_reg_pp0_iter5_or_cond_i_i_reg_1977;
        ap_reg_pp0_iter6_src_kernel_win_0_va_6_reg_2061 <= ap_reg_pp0_iter5_src_kernel_win_0_va_6_reg_2061;
        ap_reg_pp0_iter6_src_kernel_win_0_va_7_reg_2067 <= ap_reg_pp0_iter5_src_kernel_win_0_va_7_reg_2067;
        ap_reg_pp0_iter7_or_cond_i_i_reg_1977 <= ap_reg_pp0_iter6_or_cond_i_i_reg_1977;
        ap_reg_pp0_iter7_src_kernel_win_0_va_11_reg_2099 <= src_kernel_win_0_va_11_reg_2099;
        ap_reg_pp0_iter7_src_kernel_win_0_va_6_reg_2061 <= ap_reg_pp0_iter6_src_kernel_win_0_va_6_reg_2061;
        ap_reg_pp0_iter7_src_kernel_win_0_va_7_reg_2067 <= ap_reg_pp0_iter6_src_kernel_win_0_va_7_reg_2067;
        ap_reg_pp0_iter8_or_cond_i_i_reg_1977 <= ap_reg_pp0_iter7_or_cond_i_i_reg_1977;
        ap_reg_pp0_iter8_src_kernel_win_0_va_6_reg_2061 <= ap_reg_pp0_iter7_src_kernel_win_0_va_6_reg_2061;
        ap_reg_pp0_iter9_or_cond_i_i_reg_1977 <= ap_reg_pp0_iter8_or_cond_i_i_reg_1977;
        ap_reg_pp0_iter9_src_kernel_win_0_va_6_reg_2061 <= ap_reg_pp0_iter8_src_kernel_win_0_va_6_reg_2061;
        src_kernel_win_0_va_6_reg_2061 <= src_kernel_win_0_va_6_fu_1266_p3;
        src_kernel_win_0_va_7_reg_2067 <= src_kernel_win_0_va_7_fu_1280_p3;
        src_kernel_win_0_va_8_reg_2073 <= src_kernel_win_0_va_8_fu_1294_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_reg_pp0_iter1_exitcond388_i_i_reg_1950 <= exitcond388_i_i_reg_1950;
        ap_reg_pp0_iter1_or_cond_i_i_reg_1977 <= or_cond_i_i_reg_1977;
        exitcond388_i_i_reg_1950 <= exitcond388_i_i_fu_996_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond388_i_i_reg_1950 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        brmerge_i_reg_1995 <= brmerge_i_fu_1131_p2;
        or_cond_i_i_i_reg_1981 <= or_cond_i_i_i_fu_1076_p2;
        tmp_49_reg_1990 <= tmp_49_fu_1127_p1;
        x_reg_1985 <= x_fu_1119_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_pp0_iter1_exitcond388_i_i_reg_1950 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        col_assign_1_t_i_reg_2008 <= col_assign_1_t_i_fu_1146_p2;
        k_buf_0_val_3_addr_reg_2002 <= tmp_58_i_fu_1139_p1;
        k_buf_0_val_4_addr_reg_2015 <= tmp_58_i_fu_1139_p1;
        k_buf_0_val_5_addr_reg_2021 <= tmp_58_i_fu_1139_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_pp0_iter2_exitcond388_i_i_reg_1950 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        col_buf_0_val_0_0_reg_2032 <= col_buf_0_val_0_0_fu_1179_p3;
        col_buf_0_val_1_0_reg_2045 <= col_buf_0_val_1_0_fu_1197_p3;
        col_buf_0_val_2_0_reg_2053 <= col_buf_0_val_2_0_fu_1215_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_V_reg_1827 <= i_V_fu_669_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_i_fu_664_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        icmp_reg_1841 <= icmp_fu_695_p2;
        p_assign_6_1_i_reg_1879 <= p_assign_6_1_i_fu_738_p2;
        p_assign_6_2_i_reg_1897 <= p_assign_6_2_i_fu_758_p2;
        p_assign_7_1_i_reg_1892 <= p_assign_7_1_i_fu_752_p2;
        p_assign_7_2_i_reg_1910 <= p_assign_7_2_i_fu_772_p2;
        p_assign_7_i_reg_1874 <= p_assign_7_i_fu_732_p2;
        tmp_115_i_reg_1854 <= tmp_115_i_fu_713_p2;
        tmp_118_i_reg_1861 <= tmp_118_i_fu_718_p2;
        tmp_2_i_reg_1832 <= tmp_2_i_fu_675_p2;
        tmp_30_reg_1869 <= tmp_118_i_fu_718_p2[32'd11];
        tmp_32_reg_1887 <= p_assign_6_1_i_fu_738_p2[32'd11];
        tmp_35_reg_1905 <= p_assign_6_2_i_fu_758_p2[32'd11];
        tmp_93_1_i_reg_1850 <= tmp_93_1_i_fu_707_p2;
        tmp_93_i_reg_1846 <= tmp_93_i_fu_701_p2;
        ult_reg_1836 <= ult_fu_680_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_pp0_iter2_exitcond388_i_i_reg_1950 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_3_load_reg_2027 <= k_buf_0_val_3_q0;
        k_buf_0_val_4_load_reg_2040 <= k_buf_0_val_4_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_pp0_iter12_or_cond_i_i_reg_1977 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        neg_src_not_i_i_i_reg_2233 <= neg_src_not_i_i_i_fu_1533_p2;
        p_39_demorgan_i_i_i_i_reg_2227 <= p_39_demorgan_i_i_i_i_fu_1523_p2;
        p_Val2_2_reg_2222 <= p_Val2_2_fu_1476_p2;
        p_i_i_i_reg_2239 <= p_i_i_i_fu_1539_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_pp0_iter11_or_cond_i_i_reg_1977 == 1'd1) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_Val2_3_reg_2189 <= grp_fu_1626_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_pp0_iter7_or_cond_i_i_reg_1977 == 1'd1) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_Val2_5_0_1_i_reg_2134 <= grp_fu_1586_p3;
        tmp24_reg_2139 <= grp_fu_1593_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_pp0_iter8_or_cond_i_i_reg_1977 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_Val2_5_1_i_reg_2159 <= p_Val2_5_1_i_fu_1393_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_pp0_iter10_or_cond_i_i_reg_1977 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_Val2_5_2_1_i_reg_2184 <= p_Val2_5_2_1_i_fu_1414_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_pp0_iter6_or_cond_i_i_reg_1977 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        r_V_2_0_1_i_reg_2119 <= grp_fu_1576_p2;
        r_V_2_0_2_i_reg_2124 <= grp_fu_1581_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_pp0_iter7_or_cond_i_i_reg_1977 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        r_V_2_2_i_reg_2154 <= grp_fu_1600_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_predicate_op205_read_state7 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_op204_read_state7 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        reg_511 <= p_src_data_stream_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        rev_reg_1930 <= rev_fu_969_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_i_reg_1832 == 1'd1) & (icmp_reg_1841 == 1'd1) & (ap_reg_pp0_iter2_or_cond_i_i_i_reg_1981 == 1'd1) & (ap_reg_pp0_iter2_exitcond388_i_i_reg_1950 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        right_border_buf_0_1_fu_336 <= right_border_buf_0_s_fu_332;
        right_border_buf_0_2_fu_340 <= right_border_buf_0_5_fu_352;
        right_border_buf_0_3_fu_344 <= col_buf_0_val_1_0_fu_1197_p3;
        right_border_buf_0_4_fu_348 <= right_border_buf_0_3_fu_344;
        right_border_buf_0_5_fu_352 <= col_buf_0_val_2_0_fu_1215_p3;
        right_border_buf_0_s_fu_332 <= col_buf_0_val_0_0_fu_1179_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_115_i_reg_1854 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        row_assign_8_1_t_i_reg_1940 <= row_assign_8_1_t_i_fu_984_p2;
        row_assign_8_2_t_i_reg_1945 <= row_assign_8_2_t_i_fu_988_p2;
        tmp_43_reg_1935 <= tmp_43_fu_979_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_pp0_iter5_or_cond_i_i_reg_1977 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_11_reg_2099 <= src_kernel_win_0_va_2_fu_316;
        src_kernel_win_0_va_9_reg_2094 <= src_kernel_win_0_va_fu_308;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_pp0_iter4_exitcond388_i_i_reg_1950 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_17_reg_2089 <= src_kernel_win_0_va_4_fu_324;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_pp0_iter5_exitcond388_i_i_reg_1950 == 1'd0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_1_fu_312 <= src_kernel_win_0_va_fu_308;
        src_kernel_win_0_va_2_fu_316 <= ap_reg_pp0_iter5_src_kernel_win_0_va_7_reg_2067;
        src_kernel_win_0_va_3_fu_320 <= src_kernel_win_0_va_2_fu_316;
        src_kernel_win_0_va_5_fu_328 <= src_kernel_win_0_va_17_reg_2089;
        src_kernel_win_0_va_fu_308 <= ap_reg_pp0_iter5_src_kernel_win_0_va_6_reg_2061;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_pp0_iter4_exitcond388_i_i_reg_1950 == 1'd0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_4_fu_324 <= src_kernel_win_0_va_8_reg_2073;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_pp0_iter9_or_cond_i_i_reg_1977 == 1'd1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp25_reg_2169 <= grp_fu_1612_p3;
        tmp26_reg_2174 <= grp_fu_1619_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_pp0_iter8_or_cond_i_i_reg_1977 == 1'd1) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp27_reg_2164 <= grp_fu_1605_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_115_i_reg_1854 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_3_reg_1920 <= tmp_3_fu_937_p3;
        tmp_42_reg_1915 <= tmp_42_fu_913_p3;
        tmp_7_reg_1925 <= tmp_7_fu_961_p3;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_condition_pp0_exit_iter3_state8 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter3_state8 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond389_i_i_fu_664_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond389_i_i_fu_664_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1576_ce = 1'b1;
    end else begin
        grp_fu_1576_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1581_ce = 1'b1;
    end else begin
        grp_fu_1581_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1586_ce = 1'b1;
    end else begin
        grp_fu_1586_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1593_ce = 1'b1;
    end else begin
        grp_fu_1593_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1600_ce = 1'b1;
    end else begin
        grp_fu_1600_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1605_ce = 1'b1;
    end else begin
        grp_fu_1605_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1612_ce = 1'b1;
    end else begin
        grp_fu_1612_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1619_ce = 1'b1;
    end else begin
        grp_fu_1619_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1626_ce = 1'b1;
    end else begin
        grp_fu_1626_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_3_ce0 = 1'b1;
    end else begin
        k_buf_0_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_2_i_reg_1832 == 1'd1) & (icmp_reg_1841 == 1'd1) & (ap_reg_pp0_iter2_or_cond_i_i_i_reg_1981 == 1'd1) & (ap_reg_pp0_iter2_exitcond388_i_i_reg_1950 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_reg_pp0_iter2_or_cond_i_i_i_reg_1981 == 1'd1) & (tmp_93_i_reg_1846 == 1'd1) & (icmp_reg_1841 == 1'd0) & (ap_reg_pp0_iter2_exitcond388_i_i_reg_1950 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_3_ce1 = 1'b1;
    end else begin
        k_buf_0_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_2_i_reg_1832 == 1'd1) & (icmp_reg_1841 == 1'd1) & (ap_reg_pp0_iter2_or_cond_i_i_i_reg_1981 == 1'd1) & (ap_reg_pp0_iter2_exitcond388_i_i_reg_1950 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_reg_pp0_iter2_or_cond_i_i_i_reg_1981 == 1'd1) & (tmp_93_i_reg_1846 == 1'd1) & (icmp_reg_1841 == 1'd0) & (ap_reg_pp0_iter2_exitcond388_i_i_reg_1950 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_3_we1 = 1'b1;
    end else begin
        k_buf_0_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_4_ce0 = 1'b1;
    end else begin
        k_buf_0_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_2_i_reg_1832 == 1'd1) & (icmp_reg_1841 == 1'd1) & (ap_reg_pp0_iter3_or_cond_i_i_i_reg_1981 == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_reg_pp0_iter3_or_cond_i_i_i_reg_1981 == 1'd1) & (tmp_93_1_i_reg_1850 == 1'd1) & (icmp_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_4_ce1 = 1'b1;
    end else begin
        k_buf_0_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1475)) begin
        if (((tmp_2_i_reg_1832 == 1'd1) & (icmp_reg_1841 == 1'd1))) begin
            k_buf_0_val_4_d1 = k_buf_0_val_3_load_reg_2027;
        end else if (((tmp_93_1_i_reg_1850 == 1'd1) & (icmp_reg_1841 == 1'd0))) begin
            k_buf_0_val_4_d1 = ap_reg_pp0_iter3_reg_511;
        end else begin
            k_buf_0_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_2_i_reg_1832 == 1'd1) & (icmp_reg_1841 == 1'd1) & (ap_reg_pp0_iter3_or_cond_i_i_i_reg_1981 == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_reg_pp0_iter3_or_cond_i_i_i_reg_1981 == 1'd1) & (tmp_93_1_i_reg_1850 == 1'd1) & (icmp_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_4_we1 = 1'b1;
    end else begin
        k_buf_0_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_5_ce0 = 1'b1;
    end else begin
        k_buf_0_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_2_i_reg_1832 == 1'd1) & (icmp_reg_1841 == 1'd1) & (ap_reg_pp0_iter3_or_cond_i_i_i_reg_1981 == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_reg_pp0_iter3_or_cond_i_i_i_reg_1981 == 1'd1) & (tmp_93_i_reg_1846 == 1'd1) & (icmp_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_5_ce1 = 1'b1;
    end else begin
        k_buf_0_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1475)) begin
        if (((tmp_2_i_reg_1832 == 1'd1) & (icmp_reg_1841 == 1'd1))) begin
            k_buf_0_val_5_d1 = k_buf_0_val_4_load_reg_2040;
        end else if (((tmp_93_i_reg_1846 == 1'd1) & (icmp_reg_1841 == 1'd0))) begin
            k_buf_0_val_5_d1 = ap_reg_pp0_iter3_reg_511;
        end else begin
            k_buf_0_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_2_i_reg_1832 == 1'd1) & (icmp_reg_1841 == 1'd1) & (ap_reg_pp0_iter3_or_cond_i_i_i_reg_1981 == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_reg_pp0_iter3_or_cond_i_i_i_reg_1981 == 1'd1) & (tmp_93_i_reg_1846 == 1'd1) & (icmp_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_5_we1 = 1'b1;
    end else begin
        k_buf_0_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_reg_pp0_iter13_or_cond_i_i_reg_1977 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter14 == 1'b1))) begin
        p_dst_data_stream_V_blk_n = p_dst_data_stream_V_full_n;
    end else begin
        p_dst_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_reg_pp0_iter13_or_cond_i_i_reg_1977 == 1'd1) & (ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_V_write = 1'b1;
    end else begin
        p_dst_data_stream_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_kernel_val_0_V_0_blk_n = p_kernel_val_0_V_0_empty_n;
    end else begin
        p_kernel_val_0_V_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((p_kernel_val_2_V_2_empty_n == 1'b0) | (p_kernel_val_2_V_1_empty_n == 1'b0) | (p_kernel_val_2_V_0_empty_n == 1'b0) | (p_kernel_val_1_V_2_empty_n == 1'b0) | (p_kernel_val_1_V_1_empty_n == 1'b0) | (p_kernel_val_1_V_0_empty_n == 1'b0) | (p_kernel_val_0_V_2_empty_n == 1'b0) | (p_kernel_val_0_V_1_empty_n == 1'b0) | (p_kernel_val_0_V_0_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_kernel_val_0_V_0_read = 1'b1;
    end else begin
        p_kernel_val_0_V_0_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_kernel_val_0_V_1_blk_n = p_kernel_val_0_V_1_empty_n;
    end else begin
        p_kernel_val_0_V_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((p_kernel_val_2_V_2_empty_n == 1'b0) | (p_kernel_val_2_V_1_empty_n == 1'b0) | (p_kernel_val_2_V_0_empty_n == 1'b0) | (p_kernel_val_1_V_2_empty_n == 1'b0) | (p_kernel_val_1_V_1_empty_n == 1'b0) | (p_kernel_val_1_V_0_empty_n == 1'b0) | (p_kernel_val_0_V_2_empty_n == 1'b0) | (p_kernel_val_0_V_1_empty_n == 1'b0) | (p_kernel_val_0_V_0_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_kernel_val_0_V_1_read = 1'b1;
    end else begin
        p_kernel_val_0_V_1_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_kernel_val_0_V_2_blk_n = p_kernel_val_0_V_2_empty_n;
    end else begin
        p_kernel_val_0_V_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((p_kernel_val_2_V_2_empty_n == 1'b0) | (p_kernel_val_2_V_1_empty_n == 1'b0) | (p_kernel_val_2_V_0_empty_n == 1'b0) | (p_kernel_val_1_V_2_empty_n == 1'b0) | (p_kernel_val_1_V_1_empty_n == 1'b0) | (p_kernel_val_1_V_0_empty_n == 1'b0) | (p_kernel_val_0_V_2_empty_n == 1'b0) | (p_kernel_val_0_V_1_empty_n == 1'b0) | (p_kernel_val_0_V_0_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_kernel_val_0_V_2_read = 1'b1;
    end else begin
        p_kernel_val_0_V_2_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_kernel_val_1_V_0_blk_n = p_kernel_val_1_V_0_empty_n;
    end else begin
        p_kernel_val_1_V_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((p_kernel_val_2_V_2_empty_n == 1'b0) | (p_kernel_val_2_V_1_empty_n == 1'b0) | (p_kernel_val_2_V_0_empty_n == 1'b0) | (p_kernel_val_1_V_2_empty_n == 1'b0) | (p_kernel_val_1_V_1_empty_n == 1'b0) | (p_kernel_val_1_V_0_empty_n == 1'b0) | (p_kernel_val_0_V_2_empty_n == 1'b0) | (p_kernel_val_0_V_1_empty_n == 1'b0) | (p_kernel_val_0_V_0_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_kernel_val_1_V_0_read = 1'b1;
    end else begin
        p_kernel_val_1_V_0_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_kernel_val_1_V_1_blk_n = p_kernel_val_1_V_1_empty_n;
    end else begin
        p_kernel_val_1_V_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((p_kernel_val_2_V_2_empty_n == 1'b0) | (p_kernel_val_2_V_1_empty_n == 1'b0) | (p_kernel_val_2_V_0_empty_n == 1'b0) | (p_kernel_val_1_V_2_empty_n == 1'b0) | (p_kernel_val_1_V_1_empty_n == 1'b0) | (p_kernel_val_1_V_0_empty_n == 1'b0) | (p_kernel_val_0_V_2_empty_n == 1'b0) | (p_kernel_val_0_V_1_empty_n == 1'b0) | (p_kernel_val_0_V_0_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_kernel_val_1_V_1_read = 1'b1;
    end else begin
        p_kernel_val_1_V_1_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_kernel_val_1_V_2_blk_n = p_kernel_val_1_V_2_empty_n;
    end else begin
        p_kernel_val_1_V_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((p_kernel_val_2_V_2_empty_n == 1'b0) | (p_kernel_val_2_V_1_empty_n == 1'b0) | (p_kernel_val_2_V_0_empty_n == 1'b0) | (p_kernel_val_1_V_2_empty_n == 1'b0) | (p_kernel_val_1_V_1_empty_n == 1'b0) | (p_kernel_val_1_V_0_empty_n == 1'b0) | (p_kernel_val_0_V_2_empty_n == 1'b0) | (p_kernel_val_0_V_1_empty_n == 1'b0) | (p_kernel_val_0_V_0_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_kernel_val_1_V_2_read = 1'b1;
    end else begin
        p_kernel_val_1_V_2_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_kernel_val_2_V_0_blk_n = p_kernel_val_2_V_0_empty_n;
    end else begin
        p_kernel_val_2_V_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((p_kernel_val_2_V_2_empty_n == 1'b0) | (p_kernel_val_2_V_1_empty_n == 1'b0) | (p_kernel_val_2_V_0_empty_n == 1'b0) | (p_kernel_val_1_V_2_empty_n == 1'b0) | (p_kernel_val_1_V_1_empty_n == 1'b0) | (p_kernel_val_1_V_0_empty_n == 1'b0) | (p_kernel_val_0_V_2_empty_n == 1'b0) | (p_kernel_val_0_V_1_empty_n == 1'b0) | (p_kernel_val_0_V_0_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_kernel_val_2_V_0_read = 1'b1;
    end else begin
        p_kernel_val_2_V_0_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_kernel_val_2_V_1_blk_n = p_kernel_val_2_V_1_empty_n;
    end else begin
        p_kernel_val_2_V_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((p_kernel_val_2_V_2_empty_n == 1'b0) | (p_kernel_val_2_V_1_empty_n == 1'b0) | (p_kernel_val_2_V_0_empty_n == 1'b0) | (p_kernel_val_1_V_2_empty_n == 1'b0) | (p_kernel_val_1_V_1_empty_n == 1'b0) | (p_kernel_val_1_V_0_empty_n == 1'b0) | (p_kernel_val_0_V_2_empty_n == 1'b0) | (p_kernel_val_0_V_1_empty_n == 1'b0) | (p_kernel_val_0_V_0_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_kernel_val_2_V_1_read = 1'b1;
    end else begin
        p_kernel_val_2_V_1_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_kernel_val_2_V_2_blk_n = p_kernel_val_2_V_2_empty_n;
    end else begin
        p_kernel_val_2_V_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((p_kernel_val_2_V_2_empty_n == 1'b0) | (p_kernel_val_2_V_1_empty_n == 1'b0) | (p_kernel_val_2_V_0_empty_n == 1'b0) | (p_kernel_val_1_V_2_empty_n == 1'b0) | (p_kernel_val_1_V_1_empty_n == 1'b0) | (p_kernel_val_1_V_0_empty_n == 1'b0) | (p_kernel_val_0_V_2_empty_n == 1'b0) | (p_kernel_val_0_V_1_empty_n == 1'b0) | (p_kernel_val_0_V_0_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_kernel_val_2_V_2_read = 1'b1;
    end else begin
        p_kernel_val_2_V_2_read = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_2_i_reg_1832 == 1'd1) & (icmp_reg_1841 == 1'd1) & (or_cond_i_i_i_reg_1981 == 1'd1) & (ap_reg_pp0_iter1_exitcond388_i_i_reg_1950 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((or_cond_i_i_i_reg_1981 == 1'd1) & (icmp_reg_1841 == 1'd0) & (ap_reg_pp0_iter1_exitcond388_i_i_reg_1950 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        p_src_data_stream_V_blk_n = p_src_data_stream_V_empty_n;
    end else begin
        p_src_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_predicate_op205_read_state7 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_op204_read_state7 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        p_src_data_stream_V_read = 1'b1;
    end else begin
        p_src_data_stream_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((p_kernel_val_2_V_2_empty_n == 1'b0) | (p_kernel_val_2_V_1_empty_n == 1'b0) | (p_kernel_val_2_V_0_empty_n == 1'b0) | (p_kernel_val_1_V_2_empty_n == 1'b0) | (p_kernel_val_1_V_1_empty_n == 1'b0) | (p_kernel_val_1_V_0_empty_n == 1'b0) | (p_kernel_val_0_V_2_empty_n == 1'b0) | (p_kernel_val_0_V_1_empty_n == 1'b0) | (p_kernel_val_0_V_0_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond389_i_i_fu_664_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1)) & ~((ap_enable_reg_pp0_iter13 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter14 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_enable_reg_pp0_iter13 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter14 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ImagLoc_x_cast_cast_s_fu_1064_p1 = $signed(ImagLoc_x_reg_1959);

assign ImagLoc_x_fu_1023_p2 = ($signed(12'd4095) + $signed(t_V_1_cast_i_fu_992_p1));

assign OP2_V_0_1_i_fu_598_p1 = $signed(p_kernel_val_0_V_1_dout);

assign OP2_V_0_2_i_fu_602_p1 = $signed(p_kernel_val_0_V_2_dout);

assign OP2_V_0_i_fu_594_p1 = $signed(p_kernel_val_0_V_0_dout);

assign OP2_V_1_1_i_fu_610_p1 = $signed(p_kernel_val_1_V_1_dout);

assign OP2_V_1_2_i_fu_614_p1 = $signed(p_kernel_val_1_V_2_dout);

assign OP2_V_1_i_fu_606_p1 = $signed(p_kernel_val_1_V_0_dout);

assign OP2_V_2_1_i_fu_622_p1 = $signed(p_kernel_val_2_V_1_dout);

assign OP2_V_2_2_i_fu_626_p1 = $signed(p_kernel_val_2_V_2_dout);

assign OP2_V_2_i_fu_618_p1 = $signed(p_kernel_val_2_V_0_dout);

assign Range1_all_ones_fu_1454_p2 = ((p_Result_6_i_i_i_fu_1445_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_zeros_fu_1460_p2 = ((p_Result_6_i_i_i_fu_1445_p4 == 6'd0) ? 1'b1 : 1'b0);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op205_read_state7 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op204_read_state7 == 1'b1)))) | ((ap_reg_pp0_iter13_or_cond_i_i_reg_1977 == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op205_read_state7 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op204_read_state7 == 1'b1)))) | ((ap_reg_pp0_iter13_or_cond_i_i_reg_1977 == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op205_read_state7 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op204_read_state7 == 1'b1)))) | ((ap_reg_pp0_iter13_or_cond_i_i_reg_1977 == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b1)));
end

always @ (*) begin
    ap_block_state1 = ((p_kernel_val_2_V_2_empty_n == 1'b0) | (p_kernel_val_2_V_1_empty_n == 1'b0) | (p_kernel_val_2_V_0_empty_n == 1'b0) | (p_kernel_val_1_V_2_empty_n == 1'b0) | (p_kernel_val_1_V_1_empty_n == 1'b0) | (p_kernel_val_1_V_0_empty_n == 1'b0) | (p_kernel_val_0_V_2_empty_n == 1'b0) | (p_kernel_val_0_V_1_empty_n == 1'b0) | (p_kernel_val_0_V_0_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state10_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state19_pp0_stage0_iter14 = ((ap_reg_pp0_iter13_or_cond_i_i_reg_1977 == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0));
end

assign ap_block_state5_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_pp0_stage0_iter2 = (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op205_read_state7 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op204_read_state7 == 1'b1)));
end

assign ap_block_state8_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_1475 = ((ap_reg_pp0_iter3_or_cond_i_i_i_reg_1981 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_predicate_op204_read_state7 = ((or_cond_i_i_i_reg_1981 == 1'd1) & (icmp_reg_1841 == 1'd0) & (ap_reg_pp0_iter1_exitcond388_i_i_reg_1950 == 1'd0));
end

always @ (*) begin
    ap_predicate_op205_read_state7 = ((tmp_2_i_reg_1832 == 1'd1) & (icmp_reg_1841 == 1'd1) & (or_cond_i_i_i_reg_1981 == 1'd1) & (ap_reg_pp0_iter1_exitcond388_i_i_reg_1950 == 1'd0));
end

assign brmerge_i_fu_1131_p2 = (tmp_6_i_fu_1072_p2 | rev_reg_1930);

assign brmerge_i_i_i_fu_1556_p2 = (p_39_demorgan_i_not_i_fu_1551_p2 | neg_src_not_i_i_i_reg_2233);

assign brmerge_i_i_not_i_i_s_fu_1547_p2 = (p_39_demorgan_i_i_i_i_reg_2227 & neg_src_not_i_i_i_reg_2233);

assign carry_fu_1495_p2 = (tmp_8_i_i_i_fu_1489_p2 & tmp_54_fu_1469_p3);

assign col_assign_1_t_i_fu_1146_p2 = (tmp_s_fu_654_p2 - tmp_49_reg_1990);

assign col_assign_cast_i_fu_1136_p1 = $signed(x_reg_1985);

assign col_buf_0_val_0_0_fu_1179_p3 = ((ap_reg_pp0_iter2_brmerge_i_reg_1995[0:0] === 1'b1) ? k_buf_0_val_3_q0 : tmp_10_fu_1168_p5);

assign col_buf_0_val_1_0_fu_1197_p3 = ((ap_reg_pp0_iter2_brmerge_i_reg_1995[0:0] === 1'b1) ? k_buf_0_val_4_q0 : tmp_12_fu_1186_p5);

assign col_buf_0_val_2_0_fu_1215_p3 = ((ap_reg_pp0_iter2_brmerge_i_reg_1995[0:0] === 1'b1) ? k_buf_0_val_5_q0 : tmp_13_fu_1204_p5);

assign deleted_zeros_fu_1501_p3 = ((carry_fu_1495_p2[0:0] === 1'b1) ? Range1_all_ones_reg_2211 : Range1_all_zeros_reg_2217);

assign exitcond388_i_i_fu_996_p2 = ((t_V_1_reg_500 == tmp_i_fu_534_p2) ? 1'b1 : 1'b0);

assign exitcond389_i_i_fu_664_p2 = ((t_V_reg_489 == tmp_1_i_fu_540_p2) ? 1'b1 : 1'b0);

assign grp_fu_1576_p0 = OP2_V_0_1_i_reg_1768;

assign grp_fu_1576_p1 = grp_fu_1576_p10;

assign grp_fu_1576_p10 = src_kernel_win_0_va_4_fu_324;

assign grp_fu_1581_p0 = OP2_V_0_2_i_reg_1773;

assign grp_fu_1581_p1 = grp_fu_1581_p10;

assign grp_fu_1581_p10 = src_kernel_win_0_va_8_reg_2073;

assign grp_fu_1586_p0 = OP2_V_0_i_reg_1763;

assign grp_fu_1586_p1 = grp_fu_1586_p10;

assign grp_fu_1586_p10 = src_kernel_win_0_va_5_fu_328;

assign grp_fu_1593_p0 = OP2_V_1_i_reg_1778;

assign grp_fu_1593_p1 = grp_fu_1593_p10;

assign grp_fu_1593_p10 = src_kernel_win_0_va_3_fu_320;

assign grp_fu_1600_p0 = OP2_V_2_i_reg_1793;

assign grp_fu_1600_p1 = grp_fu_1600_p10;

assign grp_fu_1600_p10 = src_kernel_win_0_va_1_fu_312;

assign grp_fu_1605_p0 = OP2_V_2_1_i_reg_1798;

assign grp_fu_1605_p1 = grp_fu_1605_p10;

assign grp_fu_1605_p10 = src_kernel_win_0_va_9_reg_2094;

assign grp_fu_1612_p0 = OP2_V_1_1_i_reg_1783;

assign grp_fu_1612_p1 = grp_fu_1612_p10;

assign grp_fu_1612_p10 = ap_reg_pp0_iter7_src_kernel_win_0_va_11_reg_2099;

assign grp_fu_1619_p0 = OP2_V_1_2_i_reg_1788;

assign grp_fu_1619_p1 = grp_fu_1619_p10;

assign grp_fu_1619_p10 = ap_reg_pp0_iter7_src_kernel_win_0_va_7_reg_2067;

assign grp_fu_1626_p0 = OP2_V_2_2_i_reg_1803;

assign grp_fu_1626_p1 = grp_fu_1626_p10;

assign grp_fu_1626_p10 = ap_reg_pp0_iter9_src_kernel_win_0_va_6_reg_2061;

assign i_V_fu_669_p2 = (t_V_reg_489 + 11'd1);

assign icmp1_fu_1017_p2 = ((tmp_46_fu_1007_p4 != 10'd0) ? 1'b1 : 1'b0);

assign icmp_fu_695_p2 = ((tmp_28_fu_685_p4 != 10'd0) ? 1'b1 : 1'b0);

assign j_V_fu_1001_p2 = (t_V_1_reg_500 + 11'd1);

assign k_buf_0_val_3_address0 = tmp_58_i_fu_1139_p1;

assign k_buf_0_val_4_address0 = tmp_58_i_fu_1139_p1;

assign k_buf_0_val_5_address0 = tmp_58_i_fu_1139_p1;

assign neg_src_fu_1518_p2 = (tmp_i_i_i_fu_1512_p2 & signbit_reg_2194);

assign neg_src_not_i_i_i_fu_1533_p2 = (signbit_not_fu_1528_p2 | p_38_i_i_i_i_fu_1507_p2);

assign or_cond_i424_i_1_i_fu_837_p2 = (tmp_120_1_i_fu_833_p2 & rev2_fu_827_p2);

assign or_cond_i424_i_2_i_fu_874_p2 = (tmp_120_2_i_fu_870_p2 & rev3_fu_864_p2);

assign or_cond_i424_i_i_fu_795_p2 = (tmp_120_i_fu_791_p2 & rev1_fu_785_p2);

assign or_cond_i_i_fu_1059_p2 = (icmp_reg_1841 & icmp1_fu_1017_p2);

assign or_cond_i_i_i_fu_1076_p2 = (tmp_6_i_fu_1072_p2 & rev4_fu_1067_p2);

assign p_38_i_i_i_i_fu_1507_p2 = (carry_fu_1495_p2 & Range1_all_ones_reg_2211);

assign p_39_demorgan_i_i_i_i_fu_1523_p2 = (signbit_reg_2194 | deleted_zeros_fu_1501_p3);

assign p_39_demorgan_i_not_i_fu_1551_p2 = (p_39_demorgan_i_i_i_i_reg_2227 ^ 1'd1);

assign p_Result_6_i_i_i_fu_1445_p4 = {{grp_fu_1626_p3[36:31]}};

assign p_Val2_2_fu_1476_p2 = (p_Val2_1_reg_2201 + tmp_3_i_i_i_fu_1466_p1);

assign p_Val2_5_0_1_cast_s_fu_1387_p1 = p_Val2_5_0_1_i_reg_2134;

assign p_Val2_5_1_i_fu_1393_p2 = ($signed(tmp24_cast_fu_1390_p1) + $signed(p_Val2_5_0_1_cast_s_fu_1387_p1));

assign p_Val2_5_2_1_i_fu_1414_p2 = ($signed(tmp26_cast_fu_1411_p1) + $signed(tmp25_reg_2169));

assign p_assign_1_fu_1045_p2 = (12'd1 - t_V_1_cast_i_fu_992_p1);

assign p_assign_2_fu_1089_p2 = ($signed(tmp_10_cast_cast_i_fu_644_p1) - $signed(p_p2_i_i_cast_cast19_s_fu_1082_p1));

assign p_assign_6_1_i_fu_738_p2 = ($signed(t_V_cast_i_fu_660_p1) + $signed(12'd4094));

assign p_assign_6_2_i_fu_758_p2 = ($signed(t_V_cast_i_fu_660_p1) + $signed(12'd4093));

assign p_assign_7_1_i_fu_752_p2 = (12'd2 - t_V_cast_i_fu_660_p1);

assign p_assign_7_2_i_fu_772_p2 = (12'd3 - t_V_cast_i_fu_660_p1);

assign p_assign_7_i_fu_732_p2 = (12'd1 - t_V_cast_i_fu_660_p1);

assign p_assign_8_i_fu_815_p2 = ($signed(tmp_135_cast_cast_i_fu_572_p1) - $signed(p_p2_i425_i_cast_cast_fu_806_p1));

assign p_dst_data_stream_V_din = ((brmerge_i_i_i_fu_1556_p2[0:0] === 1'b1) ? p_mux_i_i_i_fu_1561_p3 : p_i_i_i_reg_2239);

assign p_i_i_i_fu_1539_p3 = ((neg_src_fu_1518_p2[0:0] === 1'b1) ? 8'd0 : p_Val2_2_fu_1476_p2);

assign p_mux_i_i_i_fu_1561_p3 = ((brmerge_i_i_not_i_i_s_fu_1547_p2[0:0] === 1'b1) ? p_Val2_2_reg_2222 : 8'd255);

assign p_p2_i425_i_1_i_fu_843_p3 = ((tmp_32_reg_1887[0:0] === 1'b1) ? p_assign_7_1_i_reg_1892 : p_assign_6_1_i_reg_1879);

assign p_p2_i425_i_2_i_fu_880_p3 = ((tmp_35_reg_1905[0:0] === 1'b1) ? p_assign_7_2_i_reg_1910 : p_assign_6_2_i_reg_1897);

assign p_p2_i425_i_cast_cast_fu_806_p1 = $signed(p_p2_i425_i_i_fu_801_p3);

assign p_p2_i425_i_i_fu_801_p3 = ((tmp_30_reg_1869[0:0] === 1'b1) ? p_assign_7_i_reg_1874 : tmp_118_i_reg_1861);

assign p_p2_i_i_cast_cast19_s_fu_1082_p1 = $signed(p_p2_i_i_i_reg_1971);

assign p_p2_i_i_i_fu_1051_p3 = ((tmp_48_fu_1037_p3[0:0] === 1'b1) ? p_assign_1_fu_1045_p2 : ImagLoc_x_fu_1023_p2);

assign rev1_fu_785_p2 = (tmp_29_fu_778_p3 ^ 1'd1);

assign rev2_fu_827_p2 = (tmp_31_fu_820_p3 ^ 1'd1);

assign rev3_fu_864_p2 = (tmp_34_fu_857_p3 ^ 1'd1);

assign rev4_fu_1067_p2 = (tmp_47_reg_1965 ^ 1'd1);

assign rev_fu_969_p2 = (ult_reg_1836 ^ 1'd1);

assign row_assign_8_1_t_i_fu_984_p2 = (tmp_fu_576_p2 - tmp_3_reg_1920);

assign row_assign_8_2_t_i_fu_988_p2 = (tmp_fu_576_p2 - tmp_7_reg_1925);

assign sel_tmp7_fu_1108_p2 = (tmp_6_i_not_fu_1102_p2 | tmp_47_reg_1965);

assign sel_tmp8_fu_1113_p2 = (tmp_8_i_fu_1085_p2 & sel_tmp7_fu_1108_p2);

assign sel_tmp_fu_1094_p3 = ((or_cond_i_i_i_fu_1076_p2[0:0] === 1'b1) ? ImagLoc_x_cast_cast_s_fu_1064_p1 : p_assign_2_fu_1089_p2);

assign signbit_not_fu_1528_p2 = (signbit_reg_2194 ^ 1'd1);

assign src_kernel_win_0_va_6_fu_1266_p3 = ((tmp_115_i_reg_1854[0:0] === 1'b1) ? tmp_14_fu_1258_p5 : col_buf_0_val_0_0_reg_2032);

assign src_kernel_win_0_va_7_fu_1280_p3 = ((tmp_115_i_reg_1854[0:0] === 1'b1) ? tmp_15_fu_1272_p5 : col_buf_0_val_1_0_reg_2045);

assign src_kernel_win_0_va_8_fu_1294_p3 = ((tmp_115_i_reg_1854[0:0] === 1'b1) ? tmp_18_fu_1286_p5 : col_buf_0_val_2_0_reg_2053);

assign t_V_1_cast_i_fu_992_p1 = t_V_1_reg_500;

assign t_V_cast_i_fu_660_p1 = t_V_reg_489;

assign tmp24_cast_fu_1390_p1 = tmp24_reg_2139;

assign tmp26_cast_fu_1411_p1 = tmp26_reg_2174;

assign tmp_10_cast_cast_i_fu_644_p1 = tmp_10_i_fu_638_p2;

assign tmp_10_i_fu_638_p2 = ($signed(12'd4094) + $signed(tmp_9_i_fu_630_p3));

assign tmp_115_i_fu_713_p2 = ((t_V_reg_489 > tmp_11_fu_522_p1) ? 1'b1 : 1'b0);

assign tmp_118_i_fu_718_p2 = ($signed(t_V_cast_i_fu_660_p1) + $signed(12'd4095));

assign tmp_11_fu_522_p1 = p_src_rows_V[10:0];

assign tmp_120_1_i_fu_833_p2 = (($signed(p_assign_6_1_i_reg_1879) < $signed(tmp_9_fu_518_p1)) ? 1'b1 : 1'b0);

assign tmp_120_2_i_fu_870_p2 = (($signed(p_assign_6_2_i_reg_1897) < $signed(tmp_9_fu_518_p1)) ? 1'b1 : 1'b0);

assign tmp_120_i_fu_791_p2 = (($signed(tmp_118_i_reg_1861) < $signed(tmp_9_fu_518_p1)) ? 1'b1 : 1'b0);

assign tmp_132_1_i_fu_848_p2 = (($signed(p_p2_i425_i_1_i_fu_843_p3) < $signed(tmp_9_fu_518_p1)) ? 1'b1 : 1'b0);

assign tmp_132_2_i_fu_885_p2 = (($signed(p_p2_i425_i_2_i_fu_880_p3) < $signed(tmp_9_fu_518_p1)) ? 1'b1 : 1'b0);

assign tmp_132_i_fu_810_p2 = (($signed(p_p2_i425_i_i_fu_801_p3) < $signed(tmp_9_fu_518_p1)) ? 1'b1 : 1'b0);

assign tmp_134_i_fu_558_p3 = {{tmp_11_fu_522_p1}, {1'd0}};

assign tmp_135_cast_cast_i_fu_572_p1 = tmp_135_i_fu_566_p2;

assign tmp_135_i_fu_566_p2 = (12'd2 + tmp_134_i_fu_558_p3);

assign tmp_16_fu_526_p1 = p_src_cols_V[11:0];

assign tmp_17_fu_530_p1 = p_src_cols_V[10:0];

assign tmp_1_fu_586_p3 = {{tmp_27_fu_582_p1}, {1'd0}};

assign tmp_1_i_fu_540_p2 = (11'd2 + tmp_11_fu_522_p1);

assign tmp_22_fu_546_p1 = p_src_rows_V[1:0];

assign tmp_23_fu_550_p1 = p_src_rows_V[1:0];

assign tmp_26_fu_554_p1 = p_src_cols_V[1:0];

assign tmp_27_fu_582_p1 = p_src_rows_V[0:0];

assign tmp_28_fu_685_p4 = {{t_V_reg_489[10:1]}};

assign tmp_29_fu_778_p3 = tmp_118_i_reg_1861[32'd11];

assign tmp_2_fu_926_p3 = ((tmp_132_1_i_fu_848_p2[0:0] === 1'b1) ? tmp_33_fu_853_p1 : tmp_8_fu_921_p2);

assign tmp_2_i_fu_675_p2 = ((t_V_reg_489 < tmp_11_fu_522_p1) ? 1'b1 : 1'b0);

assign tmp_31_fu_820_p3 = p_assign_6_1_i_reg_1879[32'd11];

assign tmp_33_fu_853_p1 = p_p2_i425_i_1_i_fu_843_p3[1:0];

assign tmp_34_fu_857_p3 = p_assign_6_2_i_reg_1897[32'd11];

assign tmp_36_fu_890_p1 = p_p2_i425_i_2_i_fu_880_p3[1:0];

assign tmp_37_fu_974_p2 = ($signed(tmp_23_fu_550_p1) + $signed(2'd3));

assign tmp_38_fu_894_p1 = tmp_118_i_reg_1861[1:0];

assign tmp_39_fu_897_p1 = p_p2_i425_i_i_fu_801_p3[1:0];

assign tmp_3_fu_937_p3 = ((or_cond_i424_i_1_i_fu_837_p2[0:0] === 1'b1) ? tmp_44_fu_934_p1 : tmp_2_fu_926_p3);

assign tmp_3_i_i_i_fu_1466_p1 = tmp_53_reg_2206;

assign tmp_40_fu_901_p1 = p_assign_8_i_fu_815_p2[1:0];

assign tmp_41_fu_905_p3 = ((tmp_132_i_fu_810_p2[0:0] === 1'b1) ? tmp_39_fu_897_p1 : tmp_40_fu_901_p1);

assign tmp_42_fu_913_p3 = ((or_cond_i424_i_i_fu_795_p2[0:0] === 1'b1) ? tmp_38_fu_894_p1 : tmp_41_fu_905_p3);

assign tmp_43_fu_979_p2 = (tmp_37_fu_974_p2 - tmp_42_reg_1915);

assign tmp_44_fu_934_p1 = p_assign_6_1_i_reg_1879[1:0];

assign tmp_45_fu_958_p1 = p_assign_6_2_i_reg_1897[1:0];

assign tmp_46_fu_1007_p4 = {{t_V_1_reg_500[10:1]}};

assign tmp_48_fu_1037_p3 = ImagLoc_x_fu_1023_p2[32'd11];

assign tmp_49_fu_1127_p1 = x_fu_1119_p3[1:0];

assign tmp_4_fu_945_p2 = (tmp_5_fu_648_p2 - tmp_36_fu_890_p1);

assign tmp_54_fu_1469_p3 = p_Val2_3_reg_2189[32'd30];

assign tmp_55_fu_1481_p3 = p_Val2_2_fu_1476_p2[32'd7];

assign tmp_58_i_fu_1139_p1 = $unsigned(col_assign_cast_i_fu_1136_p1);

assign tmp_5_fu_648_p2 = (tmp_1_fu_586_p3 ^ 2'd2);

assign tmp_6_fu_950_p3 = ((tmp_132_2_i_fu_885_p2[0:0] === 1'b1) ? tmp_36_fu_890_p1 : tmp_4_fu_945_p2);

assign tmp_6_i_fu_1072_p2 = (($signed(ImagLoc_x_reg_1959) < $signed(tmp_16_fu_526_p1)) ? 1'b1 : 1'b0);

assign tmp_6_i_not_fu_1102_p2 = (tmp_6_i_fu_1072_p2 ^ 1'd1);

assign tmp_7_fu_961_p3 = ((or_cond_i424_i_2_i_fu_874_p2[0:0] === 1'b1) ? tmp_45_fu_958_p1 : tmp_6_fu_950_p3);

assign tmp_8_fu_921_p2 = (tmp_5_fu_648_p2 - tmp_33_fu_853_p1);

assign tmp_8_i_fu_1085_p2 = (($signed(p_p2_i_i_i_reg_1971) < $signed(tmp_16_fu_526_p1)) ? 1'b1 : 1'b0);

assign tmp_8_i_i_i_fu_1489_p2 = (tmp_55_fu_1481_p3 ^ 1'd1);

assign tmp_93_1_i_fu_707_p2 = ((t_V_reg_489 == 11'd0) ? 1'b1 : 1'b0);

assign tmp_93_i_fu_701_p2 = ((t_V_reg_489 == 11'd1) ? 1'b1 : 1'b0);

assign tmp_9_fu_518_p1 = p_src_rows_V[11:0];

assign tmp_9_i_fu_630_p3 = {{tmp_17_fu_530_p1}, {1'd0}};

assign tmp_fu_576_p2 = ($signed(2'd3) + $signed(tmp_22_fu_546_p1));

assign tmp_i_fu_534_p2 = (11'd2 + tmp_17_fu_530_p1);

assign tmp_i_i_i_fu_1512_p2 = (p_38_i_i_i_i_fu_1507_p2 ^ 1'd1);

assign tmp_s_fu_654_p2 = ($signed(2'd3) + $signed(tmp_26_fu_554_p1));

assign ult_fu_680_p2 = ((t_V_reg_489 < tmp_11_fu_522_p1) ? 1'b1 : 1'b0);

assign x_fu_1119_p3 = ((sel_tmp8_fu_1113_p2[0:0] === 1'b1) ? p_p2_i_i_cast_cast19_s_fu_1082_p1 : sel_tmp_fu_1094_p3);

endmodule //Filter2D
